### ISSUE TITLE
Relicence under LGPL?

### ISSUE THREAD

**Issue by domdfcoding** [niklasf/indexed.py#1]
Would you be willing to relicense this under the terms of the GNU LGPL v3? I'd like to use this in a project but I can't without making my project GPL too.

See [https://choosealicense.com/licenses/lgpl-3.0/](https://choosealicense.com/licenses/lgpl-3.0/) for more info on the LGPL v3.

**Comment by niklasf** [comment]
Usually I would not, but it seems fair, given that this library includes a lot of code from CPython itself. For the same reason PSFL is the most permissive that can be done.

So: Changed to PSFL. Hope this meets your needs.
