### ISSUE TITLE
keys() and values() returns the same thing that values()

### ISSUE THREAD

**Issue by M4daray** [niklasf/indexed.py#5]
Hello, here a small example
```
from indexed import IndexedOrderedDict
>>> b = dict(x=1, y=2)
>>> b.keys()
dict_keys(['x', 'y'])
>>> a = IndexedOrderedDict(x=1, y=2)
>>> a.keys()
IndexedKeysView(IndexedOrderedDict([('x', 1), ('y', 2)]))
```

I want to iterate over the keys of the dict, but to access them I have to iterate over a.keys()[:] which seems to me strange. Is this the normal behavior or a bug ?

Thank you for this nice project.

**Comment by M4daray** [comment]
I'm an idiot, I just have to `list(a.keys())` to iterate, just like a normal dict ...

**Comment by niklasf** [comment]
Iterating over a bare `a.keys()` should work, too, but verifying that requires actual iteration, not just looking at the string representation via `>>> a.keys()`. Please let me know if it doesn't work.
